### ISSUE TITLE
Synchronize with taiga issues board

### ISSUE THREAD

**Issue by gandhiano** [TransforMap/transformap-api#2]
We want issues posted on the github to be integrated with [Transformap's taiga.io project](https://tree.taiga.io/project/transformap).

This has been setup following the [taiga documentation](https://taiga.io/support/github-integration/). The taiga.io GitHub integration also allows push events with reference to elements on taiga to be posted there.

**Comment by gandhiano** [comment]
One-way sync to taiga.io through GitHub integration works perfectly and even adds reference to the original issue here. Does it make sense the effort to get the sync back or should we consider the issues on Github only as a collect point?

**Comment by almereyda** [comment]
Yes, we don't have enough resoureces to push Taiga into the desired direction as fast as expected. Closing for now; recreate when appropriate.

**Comment by almereyda** [comment]
I have [disabled linking to the Taiga project](https://tree.taiga.io/project/transformap/issue/257), as it is more about the whole of transformap and less about the API.

**Comment by gandhiano** [comment]
## Why? I found this very useful and would like to keep it on

Gualter Baptista

**Comment by species** [comment]
I would also not push everything to taiga, as the api is not the only active project on github/transformap! 
When the API has its geo-capapilities implemented, my focus will switch back to the demo maps, and there are a few other repositories too, where work happens.

I don't think it does make much sense to link all active transformap/ - repos to taiga, or what do you think?

**Comment by gandhiano** [comment]
## I like the idea of linking all repos there, as it keeps an overall view of the different components and we can promote issues to stories. What is disturbing you in this workflow?

Gualter Baptista
