### ISSUE TITLE
API call "create"

### ISSUE THREAD

**Issue by species** [TransforMap/transformap-api#3]
implement "create a new POI" api call

The following requirements have to be met for this operation to succeed:
- the user account has "write" capabilities (is not banned)
- check if the supplied JSON file matches the required format
- check if the coordinates are in the allowed range
- check if there is at least the name of the POI set in the tags (we shouldn't allow empty POIs)

API should do the following while adding it to the DB
- add timestamp
- add user-id
- ? add licence chosen by the user

Should return the ID the DB assigned to it.

**Comment by almereyda** [comment]
This is implemented since 1d56310.

Let's close this issue for now and reopen a new one with a properly formulated issue.
