### ISSUE TITLE
Add filter API endpoint

### ISSUE THREAD

**Issue by species** [TransforMap/transformap-api#35]
A big feature we need is filtering according to attributes. So we need an endpoint that allows filtering the whole DB based on attributes, (similar functionality to the Overpass API of OpenStreetMap). Endpoint can be called "filter/" or similar.

**Takes**: one or more attributes (key=value) - they should be treated as AND-combined criteria.
-  e.g. ["SSEDAS_PARTNER"="Eeeti","CATEGORY-TAG1"="cooperative"] should return every item that is from Eeti and is a cooperative.

**Returns**: all items as geojson Feature Collection.
- Bonus: should return the query as attribute of the Feature Collection too.

**Comment by species** [comment]
Basic support for querying (a single key=value or key) added in 5883bf60d7d40c75c9f632182eb063962e5ac8bb in branch tag-index.

Caveat: no unit tests yet.

Waiting merge of dokku branch for a PR to master.

**Comment by almereyda** [comment]
Closed via #40.
