### ISSUE TITLE
API call "read"

### ISSUE THREAD

**Issue by species** [TransforMap/transformap-api#4]
Types of queries:
- or fetch a single item by its already known id
  - later on, fetch previous versions  
- either a BBOX query (has to be postponed until geocouch is ready)
  - there has to be a flag for retrieving all objects (including deleted) or just "living" ones

Questions for the BBOX query: should it be possible to query the DB according to the following criteria
- all objects from a specific user ID
- all objects created/modified in a given timeframe (e.g. to create DB diffs)
- to query according to specific "tags" set
  - ? combination of tags
  - ? regex filters

API should do
- convert timestamp (if it is in ms since epoch) to human readable format
- add version number of object (if not stored in DB)
- add expanded licence string
- return (geo-)json object

**Comment by almereyda** [comment]
Let's consider this issue also a little overweight, a so called _epic_, and close it since a basic GET interface is available since 1bdaaa8.

Let's track our development user stories, which are not neccessarily bugs, via the various other project maintenance platforms OR with a series of smaller, more precise issues.

**Comment by gandhiano** [comment]
Apologies to comment on a closed issue, but I can only support this. Lets use proper user stories on [Transformap taiga.io board](https://tree.taiga.io/project/transformap) for agreeing and keeping overview of features development, while keeping the issue tracker for... well, issues with the code :)

Making it that way helps us not only to have better structure, but also more collaboration and collective decision on the way to go (agreeing on user stories as human-language features, then describing collectively the tasks to be done).

Thanks for cleaning up this queue @almereyda
