### ISSUE TITLE
Can a media file be "assigned" to more than one POI?

### ISSUE THREAD

**Issue by acorbi** [TransforMap/transformap-api#46]
@almereyda while adapting my [definition](https://github.com/acorbi/transformap-editor/blob/impl-mocking-libs/app/lib/MMS_API.md) for the `media`endpoint based on the fixtures and comments from your PR on https://github.com/TransforMap/data.transformap.co/pull/45, the question whether a media file can be assigned to multiple POIs came to my mind.

According to the workflow discussed on your PR, in order to upload a new media the user client would first *POST* to `/media` and then *PUT* to `/place` to assign the media file to an existing POI.

Do we want to allow a certain media file to be "assigned" to several POIs? I tend to think that we should technically allow for this in order to keep the system flexible but that there would possibly not be any use case that justifies this hability.

What do you think?

**Comment by gandhiano** [comment]
If the implementation offers no additional complexity, it is definitely the way to go.

**Comment by almereyda** [comment]
I can imagine organisations adding their logo or the likes to multiple places. Therefore, the decoupling of the flat media UUID and place UUID namespaces allows for various use cases as outlined above, and does not involve additional development. Closing, as no open question is to be solved here.

**Comment by acorbi** [comment]
@almereyda  @gandhiano  :+1:
