### ISSUE TITLE
Search by username

### ISSUE THREAD

**Issue by jum-s** [TransforMap/transformap-api#47]
A user type is created. 
Posting a new user through  `breq.post(CONFIG.server.url() + '/user', newUser)` is working. 
But how to look for a user thing that has the name "foo" ? Is it possible with those methods in [build_lib](https://github.com/TransforMap/data.transformap.co/blob/master/server/controllers/things/build_lib.js)
My best try without documentation was something like `db.viewByKey('byAttributes',['user', 'name'])`

**Comment by jum-s** [comment]
everything is in this [file](
https://github.com/TransforMap/data.transformap.co/blob/425-oauth2-provider/server/controllers/things/models/types/user.js),
so far a mocked user is the answer but i would like to create this [findOneByUsername](https://github.com/TransforMap/data.transformap.co/blob/425-oauth2-provider/server/controllers/things/models/types/user.js#L32)
```js
  findOneByUsername: function (username) {
    // Fake user
    const wannabeUser = {
      journal: 'bcf4f3ff325d7c8c7a5f67320e01a3f0',
      data:
       { name: 'moleculor',
         email: 'vincent.jumeaux@riseup.net',
         provider: 'https://lab.allmende.io/u/moleculor' },
      author: 'Douglas Adams',
      description: 'Have fun, and thanks for all the fish!',
      context: 'version',
      timestamp: 1504438602552
    }
    if (wannabeUser.data.name == username) {
      _.success(wannabeUser.data.name, 'existing user')
      return promises_.resolve(wannabeUser)
    } else {
      _.error('user not found')
      // not returning an Error object as it triggers a 500 response
      return promises_.reject(wannabeUser)
    }
  }
```

**Comment by maxlath** [comment]
there is no trace of a `users` CouchDB database being initialized in [db/init.js `dbsList`](https://github.com/TransforMap/data.transformap.co/blob/5fb65ad7dbf3214fc75a9fb88fad24af5d031c82/db/init.js#L6-L11): it could be simply something like `{ name: 'users', designDocs: [ 'users' ] }`.

Then [couchInit](https://github.com/TransforMap/data.transformap.co/blob/5fb65ad7dbf3214fc75a9fb88fad24af5d031c82/db/init.js#L14) will be looking for the file `db/design_docs/users.json` that you need to create.
See [CouchDB Design docs documentation](http://docs.couchdb.org/en/2.0.0/couchapp/ddocs.html), but read only about views, the other functions - reduce, re-reduce, list, show - aren't much needed (the last two being mostly legacy).
You can take inspiration on the existing [journals design doc](https://github.com/TransforMap/data.transformap.co/blob/5fb65ad7dbf3214fc75a9fb88fad24af5d031c82/db/design_docs/journals.json) or [inventaire's own users design doc](https://github.com/inventaire/inventaire/blob/master/db/couchdb/design_docs/users.json).

**Comment by maxlath** [comment]
Then, as for [things](https://github.com/TransforMap/data.transformap.co/blob/5fb65ad7dbf3214fc75a9fb88fad24af5d031c82/server/controllers/things/build_lib.js), you can have a lib file that handles all the interactions with the users database, thus initializing a [db object](https://github.com/TransforMap/data.transformap.co/blob/5fb65ad7dbf3214fc75a9fb88fad24af5d031c82/server/controllers/things/build_lib.js#L4) like so:
```js
const db = __.require('lib', 'db/db')('users', 'users')
```

**Comment by jum-s** [comment]
great answer thx
