### ISSUE TITLE
API call "update"

### ISSUE THREAD

**Issue by species** [TransforMap/transformap-api#5]
does update an existing POI with known ID
- same checks for data validity as in "create" call
- reject if new object does not differ from the current one

API should do the following
- create new object
- increase version number
- set link to old ID
- in the old object, mark it as "obsoletw" and set link to new ID

returns new version number or rejects if there is an editing conflict (There is a newer version on the server than in the client's cache)

**Comment by species** [comment]
added "reject if new object does not differ from the current one"

**Comment by almereyda** [comment]
Implemented since 0ab1a16

As this is not an issue anymore, closing. Reopen with natural language description of the issue.
